### ISSUE TITLE
[체크리스트] 작동이 필요한 기능들 (11.07. 오후 6시 merge 기준)

### ISSUE THREAD

**Issue by incolore9** [ormcamp-fe-3rd/bunnies-page#47]
### home
- [x] home의 멤버 포토 카드를 클릭했을 때 별도의 액션 없음
- [x] home의 album 섹션에서 album 페이지로 넘어가는 링크 붙여도 괜찮을 것 같습니다.
- [x] 모달 팝업 창은 시각적으로 컴퓨터 외부만 블러처리하고, 창이 닫히는 건 창 외부 아무 곳을 클릭해도 실행되면 사용성이 올라갈 것 같습니다.
- [x] 헤더 부분 영상 자동 재생되지 않음 (각자 확인 필요)
*이 부분은 onload 함수 때문인 것 같다고 해주셨는데, main pull 이후에 onload가 없는 상황임에도 재생되지 않습니다. 저만 그럴 수도 있는 것이고 슬기님은 아침 보고 시간에 작동했던 것 보면 개인차가 있어 보입니다.

### member
- [x] 멤버 페이지의 멤버 카드 내 메세지가 더미텍스트 상태임
- [x] 메세지 기능에서 하드코딩으로 선입력해놓은 메세지들이 아직 로렘입숨 상태임

### album
- [x] 네비바 없음

**Comment by baaanjy** [comment]
home mv 관련하여, 저는 처음 페이지가 로드될때는 자동재생이 되지 않고, 다른 메뉴에 갔다가 홈으로 돌아왔을때는 자동재생이 됩니다

**Comment by naseulgee** [comment]
home mv 관하여2, 체크해보도록 하겠습니다!
album 관하여, PR 진행하도록 하겠습니다

**Comment by hyeoholee** [comment]
home/album에 이미지 클릭시에도 앨범섹션으로 이동하고
재생버튼을 따로 추가해서 그것도 앨범섹션으로 이동하게 추가했습니다.

**Comment by naseulgee** [comment]
### header
- [ ] 헤더 X(구 트위터) 링크 변경
  - `https://x.com/NewJeans_ADOR`
### album
- [ ] 영수증 회전 각도 범위 줄이기
- [ ] 헤더 셀렉트 메뉴 변경 `Main` -> `Albums`

**Comment by naseulgee** [comment]
### home
- [ ] 메인 멤버 카드 영역이 큰 모니터에서 벗어나 보임

**Comment by baaanjy** [comment]
메인 멤버 카드 클릭시 멤버페이지로 이동하는 부분 추가했습니다
